# This workflow will build a Java project with Ant using GraalVM
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Build with GraalVM and Apache Ant

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    env:
      CUSTOM_WORKSPACE: "G:\actions-runner-workspace"

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Apache Ant
        run: |
          choco install ant -y

      - name: Download and Extract GraalVM
        run: |
          Copy-Item -Path "G:\actions-runner-workspace\_tool\graalvm-community-openjdk-22.0.1+8.1" -Destination "G:\actions-runner-workspace\graalvm"

      - name: Set GRAALVM_HOME
        run: |
          echo "GRAALVM_HOME=$env:USERPROFILE\graalvm\graalvm-ce-java11-22.0.1" >> $GITHUB_ENV

      - name: Print Custom Workspace
        run: |
          echo "Custom Workspace: $CUSTOM_WORKSPACE"

      - name: Build with Apache Ant
        run: |
          cd $env:CUSTOM_WORKSPACE\l2walker\l2walker\build
          ant -noinput -buildfile build.xml

      - name: Move JAR to root directory
        run: |
          mv $env:CUSTOM_WORKSPACE\l2walker\l2walker\build\l2walker.jar $env:CUSTOM_WORKSPACE\l2walker\l2walker\l2walker\l2walker.jar

      - name: Add JAR to Git
        run: |
          git add $env:CUSTOM_WORKSPACE\l2walker\l2walker\l2walker\l2walker.jar

      - name: Commit changes
        run: |
          git commit -m "Add l2walker.jar"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
